services:
  postgres:
    image: postgres:latest #TODO set specific version
    container_name: pigeon_mail_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init_database.sql:/docker-entrypoint-initdb.d/init_database.sql

volumes:
  postgres_data: